name: aws-platform/ec2 CI/CD

on:
  pull_request:
    branches: [develop, main]
    paths:
      - "aws-platform/ec2/**"
      - "aws-platform/modules/ec2/**"
      - .github/workflows/ec2-ci.yml
      - .github/workflows/terraform-reusable.yml
  push:
    branches: [develop, main]
    paths:
      - "aws-platform/ec2/**"
      - "aws-platform/modules/ec2/**"
      - .github/workflows/ec2-ci.yml
      - .github/workflows/terraform-reusable.yml

jobs:
  terraform:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      working_directory: aws-platform/ec2

