name: lab/streaming-host CI/CD

on:
  pull_request:
    branches: [develop, main]
    paths:
      - "lab/streaming-host/**"
      - "modules/ec2/**"
      - .github/workflows/lab-streaming-host-ci.yml
      - .github/workflows/terraform-reusable.yml
  push:
    branches: [develop, main]
    paths:
      - "lab/streaming-host/**"
      - "modules/ec2/**"
      - .github/workflows/lab-streaming-host-ci.yml
      - .github/workflows/terraform-reusable.yml

jobs:
  terraform:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      working_directory: lab/streaming-host

