name: aws-platform/pipelines/webevents-streaming CI/CD

on:
  pull_request:
    branches: [develop, main]
    paths:
      - "aws-platform/pipelines/webevents-streaming/**"
      - "aws-platform/modules/glue-job/**"
      - .github/workflows/pipeline-webevents-streaming-ci.yml
      - .github/workflows/terraform-reusable.yml
  push:
    branches: [develop, main]
    paths:
      - "aws-platform/pipelines/webevents-streaming/**"
      - "aws-platform/modules/glue-job/**"
      - .github/workflows/pipeline-webevents-streaming-ci.yml
      - .github/workflows/terraform-reusable.yml

jobs:
  terraform:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      working_directory: aws-platform/pipelines/webevents-streaming
      needs_opensearch_password: true
