name: platform/aws/network CI/CD

on:
  pull_request:
    branches: [develop, main]
    paths:
      - "platform/aws/network/**"
      - "platform/aws/modules/vpc/**"
      - .github/workflows/platform-aws-network-ci.yml
      - .github/workflows/terraform-reusable.yml
  push:
    branches: [develop, main]
    paths:
      - "platform/aws/network/**"
      - "platform/aws/modules/vpc/**"
      - .github/workflows/platform-aws-network-ci.yml
      - .github/workflows/terraform-reusable.yml

jobs:
  terraform:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      working_directory: platform/aws/network

