name: sources/rds CI/CD

on:
  pull_request:
    branches: [develop, main]
    paths:
      - "sources/rds/**"
      - "modules/rds/**"
      - .github/workflows/sources-rds-ci.yml
      - .github/workflows/terraform-reusable.yml
  push:
    branches: [develop, main]
    paths:
      - "sources/rds/**"
      - "modules/rds/**"
      - .github/workflows/sources-rds-ci.yml
      - .github/workflows/terraform-reusable.yml

jobs:
  terraform:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      working_directory: sources/rds
      needs_rds_password: true
