name: workloads/dms CI/CD

on:
  pull_request:
    branches: [develop, main]
    paths:
      - "workloads/dms/**"
      - "modules/dms/**"
      - .github/workflows/workload-dms-ci.yml
      - .github/workflows/terraform-reusable.yml
  push:
    branches: [develop, main]
    paths:
      - "workloads/dms/**"
      - "modules/dms/**"
      - .github/workflows/workload-dms-ci.yml
      - .github/workflows/terraform-reusable.yml

jobs:
  terraform:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      working_directory: workloads/dms
      needs_rds_password: true
