name: workloads/federated-query CI/CD

on:
  pull_request:
    branches: [develop, main]
    paths:
      - "modules/rds/**"
      - "workloads/federated-query/**"
      - .github/workflows/workload-federated-query-ci.yml
      - .github/workflows/terraform-reusable.yml
  push:
    branches: [develop, main]
    paths:
      - "modules/rds/**"
      - "workloads/federated-query/**"
      - .github/workflows/workload-federated-query-ci.yml
      - .github/workflows/terraform-reusable.yml

jobs:
  terraform:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      working_directory: workloads/federated-query/aws/infra
      needs_rds_password: true
